Marazzo/Models/Banner.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Marazzo.Models
{
    public class Banner
    {
        [Key]
        public int Id { get; set; }
        [MaxLength(50),Required]
        public string Title { get; set; }
        [MaxLength(50), Required]
        public string Name { get; set; }
        [MaxLength(50), Required]
        public string Description { get; set; }
        [MaxLength(250)]
        public string Image { get; set; }
        [NotMapped]
        public IFormFile ImageFile { get; set; }

        [ForeignKey("Subcategory")]
        public int? SubcategoryId { get; set; }
        public Subcategory Subcategory { get; set; }

    }
}

Marazzo/Areas/admin/Controllers/BannerController.cs
using Marazzo.Data;
using Marazzo.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace Marazzo.Areas.admin.Controllers
{
    [Area("admin")]
    public class BannerController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public BannerController(AppDbContext context,IWebHostEnvironment webHostEnvironment )
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }

        public IActionResult Index()
        {
            List<Banner> banners = _context.Banners.ToList();
            return View(banners);
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Banner model)
        {
            if (ModelState.IsValid)
            {
                if (model.ImageFile.ContentType == "image/jpg" || model.ImageFile.ContentType == "image/jpeg" || model.ImageFile.ContentType == "image/png")
                {
                    if (model.ImageFile.Length <= 3145728)
                    {

                        string fileName = System.Guid.NewGuid() + "" + model.ImageFile.FileName;
                        string filePath = Path.Combine(_webHostEnvironment.WebRootPath,"Uploads", fileName);
                        using (var stream=new FileStream(filePath,FileMode.Create))
                        {
                            model.ImageFile.CopyTo(stream);
                        }
                        model.Image = fileName;
                        _context.Banners.Add(model);
                        _context.SaveChanges();
                        return RedirectToAction("index");





                    }
                    else {
                        ModelState.AddModelError("","Size of the file is too big");
                        return View(model);
                    }
                }
                else {

                    ModelState.AddModelError("", "Type of image file is not supported");
                    return View(model);
                }
            }
            else
            {
                return View(model);
            }
            return View();
        }
        public IActionResult Update(int id)
        {
            return View(_context.Banners.Find(id));
        }
        [HttpPost]
        public IActionResult Update(Banner model)
        {
            if (ModelState.IsValid)
            {
                if (model.ImageFile != null)
                {
                    if (model.ImageFile.ContentType == "image/jpeg" || model.ImageFile.ContentType == "image/png" || model.ImageFile.ContentType == "image/jpg")
                    {
                        if (model.ImageFile.Length <= 3145728)
                        {
                            string oldImagePath = Path.Combine(_webHostEnvironment.WebRootPath, "Uploads", model.Image);
                            if (System.IO.File.Exists(oldImagePath))
                            {
                                System.IO.File.Delete(oldImagePath);
                            }




                            string fileName = Guid.NewGuid() + "-" + model.ImageFile.FileName;
                            string filePath = Path.Combine(_webHostEnvironment.WebRootPath, "Uploads", fileName);
                            using (var stream = new FileStream(filePath, FileMode.Create))
                            {
                                model.ImageFile.CopyTo(stream);
                            }
                            model.Image = fileName;
                            _context.Banners.Update(model);
                            _context.SaveChanges();
                            return RedirectToAction("index");
                        }
                        else
                        {
                            ModelState.AddModelError("", "Image is too big");
                            return View(model);
                        }

                    }
                    else
                    {
                        ModelState.AddModelError("", "Type of image file is not supported");
                        return View(model);

                    }
                }
                else
                {

                    _context.Banners.Update(model);
                    _context.SaveChanges();
                    return RedirectToAction("index");

                }



            }

            else
            {
                return View(model);
            }

        }
        public IActionResult Delete(int id)
        {
            Banner funbanner = _context.Banners.Find(id);
            string? oldImagePath = Path.Combine(_webHostEnvironment.WebRootPath, "Uploads", funbanner.Image);
            if (System.IO.File.Exists(oldImagePath))
            {
                System.IO.File.Delete(oldImagePath);
                _context.Banners.Remove(funbanner);
                _context.SaveChanges();
            }
            else
            {
                _context.Banners.Remove(funbanner);
                _context.SaveChanges();
            }


            return RedirectToAction("index");
        }

    }
}

Marazzo/Areas/admin/Views/Banner/Create.cshtml
@model Banner
@{
    Layout = "~/Areas/admin/Views/Shared/_Layout.cshtml";
}

<form asp-area="admin" asp-controller="Banner" asp-action="create" method="post" enctype="multipart/form-data">
    <div class="form-group">
        <label asp-for="@Model.ImageFile">Blog image</label>
        <input class="form-control" asp-for="@Model.ImageFile">
        <label asp-for="@Model.Title">Blog title</label>
        <input class="form-control" asp-for="@Model.Title">
        <label asp-for="@Model.Name">Blog title</label>
        <input class="form-control" asp-for="@Model.Name">
        <label asp-for="@Model.Description">Blog title</label>
        <input class="form-control" asp-for="@Model.Description">
    </div>

    <button type="submit" class="btn btn-primary">Create</button>
</form>

Marazzo/Areas/admin/Views/Banner/Index.cshtml
@model List<Banner>
@{
    Layout = "~/Areas/admin/Views/Shared/_Layout.cshtml";
}

<a asp-area="admin" asp-controller="Banner" asp-action="create" class="btn btn-primary">Create</a>

<table class="table">
    <thead>
        <tr>
            <th scope="col">Id</th>
            <th scope="col">Image</th>
            <th scope="col">Title</th>
            <th scope="col">Name</th>
            <th scope="col">Description</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>

                <td>@item.Id</td>
                <td><img src="~/Uploads/@item.Image" alt="Alternate Text" style="max-width:150px; max-height:150px" /></td>
                <td>@item.Title</td>
                <td>@(item.Description.Length>50? item.Description.Substring(0,50):item.Description)</td>
                <td><a asp-controller="Banner" asp-area="admin" asp-action="update" asp-route-id="@item.Id" type="button" class="btn btn-success">Update</a></td>
                <td><a asp-controller="Banner" asp-area="admin" asp-action="delete" asp-route-id="@item.Id" onclick="return confirm('Are you sure?')" type="button" class="btn btn-danger">Delete</a></td>
            </tr>

        }

    </tbody>
</table>

Marazzo/Areas/admin/Views/Banner/Update.cshtml
@model Banner
@{
    Layout = "~/Areas/admin/Views/Shared/_Layout.cshtml";
}

<form asp-area="admin" asp-controller="Banner" asp-action="Update" method="post" enctype="multipart/form-data">
    <div class="form-group">
        <img src="~/Uploads/@Model.Image" alt="Alternate Text" width="100px" />
        <label asp-for="@Model.ImageFile">Blog image</label>
        <input class="form-control" asp-for="@Model.ImageFile">
        <label asp-for="@Model.Title">Blog title</label>
        <input class="form-control" asp-for="@Model.Title">
        <label asp-for="@Model.Name">Blog title</label>
        <input class="form-control" asp-for="@Model.Name">
        <label asp-for="@Model.Description">Description</label>
        <input class="form-control" asp-for="@Model.Description">
        <input asp-for="@Model.Id" hidden />
        <input asp-for="@Model.Image" hidden />
    </div>

    <button type="submit" class="btn btn-primary">Update</button>
</form>